/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2022-05-19 16:06:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.template.view.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _005findex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1650695708703L));
    _jspx_dependants.put("jar:file:/C:/Users/Admin/Downloads/springmvc-hibernate-mssql-main/Nhom15_DHKTPM15BTT_WWW/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Nhom15_DHKTPM15BTT_WWW/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153359882000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("(function($) {\n");
      out.write("	  'use strict';\n");
      out.write("	  $(function() {\n");
      out.write("	    if ($(\"#audience-chart\").length) {\n");
      out.write("	      var AudienceChartCanvas = $(\"#audience-chart\").get(0).getContext(\"2d\");\n");
      out.write("	      var AudienceChart = new Chart(AudienceChartCanvas, {\n");
      out.write("	        type: 'bar',\n");
      out.write("	        data: {\n");
      out.write("	          labels: [\n");
      out.write("	        	  ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	        	  ],\n");
      out.write("	          datasets: [\n");
      out.write("	            {\n");
      out.write("	              type: 'line',\n");
      out.write("	              fill: false,\n");
      out.write("	              data: [\n");
      out.write("	            	  ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write(",\n");
      out.write("	            	  ],\n");
      out.write("	              borderColor: '#ff4c5b'\n");
      out.write("	            },\n");
      out.write("	            {\n");
      out.write("	              label: 'Min Price',\n");
      out.write("	              data: [\n");
      out.write("	            	  ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	            	  ],\n");
      out.write("	              backgroundColor: '#6640b2'\n");
      out.write("	            },\n");
      out.write("	            {\n");
      out.write("	                label: 'Max Price',\n");
      out.write("	                data: [\n");
      out.write("	                	 ");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write(", \n");
      out.write("	                	],\n");
      out.write("	                backgroundColor: '#1cbccd'\n");
      out.write("	              }\n");
      out.write("	          ]\n");
      out.write("	        },\n");
      out.write("	        options: {\n");
      out.write("	          responsive: true,\n");
      out.write("	          maintainAspectRatio: true,\n");
      out.write("	          layout: {\n");
      out.write("	            padding: {\n");
      out.write("	              left: 0,\n");
      out.write("	              right: 0,\n");
      out.write("	              top: 20,\n");
      out.write("	              bottom: 0\n");
      out.write("	            }\n");
      out.write("	          },\n");
      out.write("	          scales: {\n");
      out.write("	            yAxes: [{\n");
      out.write("	              display: true,\n");
      out.write("	              gridLines: {\n");
      out.write("	                display: true,\n");
      out.write("	                drawBorder: false,\n");
      out.write("	                color: \"#f8f8f8\",\n");
      out.write("	                zeroLineColor: \"#f8f8f8\"\n");
      out.write("	              },\n");
      out.write("	              ticks: {\n");
      out.write("	                display: true,\n");
      out.write("	                min: 0,\n");
      out.write("	                max: 400,\n");
      out.write("	                stepSize: 100,\n");
      out.write("	                fontColor: \"#b1b0b0\",\n");
      out.write("	                fontSize: 10,\n");
      out.write("	                padding: 10\n");
      out.write("	              }\n");
      out.write("	            }],\n");
      out.write("	            xAxes: [{\n");
      out.write("	              stacked: false,\n");
      out.write("	              ticks: {\n");
      out.write("	                beginAtZero: true,\n");
      out.write("	                fontColor: \"#b1b0b0\",\n");
      out.write("	                fontSize: 10\n");
      out.write("	              },\n");
      out.write("	              gridLines: {\n");
      out.write("	                color: \"rgba(0, 0, 0, 0)\",\n");
      out.write("	                display: false\n");
      out.write("	              },\n");
      out.write("	              barPercentage: .9,\n");
      out.write("	              categoryPercentage: .7,\n");
      out.write("	            }]\n");
      out.write("	          },\n");
      out.write("	          legend: {\n");
      out.write("	            display: false\n");
      out.write("	          },\n");
      out.write("	          elements: {\n");
      out.write("	            point: {\n");
      out.write("	              radius: 3,\n");
      out.write("	              backgroundColor: '#ff4c5b'\n");
      out.write("	            }\n");
      out.write("	          }\n");
      out.write("	        },\n");
      out.write("	      });\n");
      out.write("	    }\n");
      out.write("		   \n");
      out.write("	    if ($(\"#balance-chart\").length) {\n");
      out.write("	      var areaData = {\n");
      out.write("	        labels: [\n");
      out.write("	        	");
      if (_jspx_meth_c_005fforEach_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	        	],\n");
      out.write("	        datasets: [\n");
      out.write("	          {\n");
      out.write("	            data: [\n");
      out.write("	            	 ");
      if (_jspx_meth_c_005fforEach_005f5(_jspx_page_context))
        return;
      out.write(", \n");
      out.write("	            	\n");
      out.write("	            	],\n");
      out.write("	            borderColor: [\n");
      out.write("	              '#1faf47'\n");
      out.write("	            ],\n");
      out.write("	            borderWidth: 3,\n");
      out.write("	            fill: false,\n");
      out.write("	            label: \"services\"\n");
      out.write("	          },\n");
      out.write("	        ]\n");
      out.write("	      };\n");
      out.write("	      var areaOptions = {\n");
      out.write("	        responsive: true,\n");
      out.write("	        maintainAspectRatio: true,\n");
      out.write("	        plugins: {\n");
      out.write("	          filler: {\n");
      out.write("	            propagate: false\n");
      out.write("	          }\n");
      out.write("	        },\n");
      out.write("	        scales: {\n");
      out.write("	          xAxes: [{\n");
      out.write("	            display: true,\n");
      out.write("	            ticks: {\n");
      out.write("	              display: false,\n");
      out.write("	            },\n");
      out.write("	            gridLines: {\n");
      out.write("	              display: false,\n");
      out.write("	              drawBorder: false,\n");
      out.write("	              color: 'transparent',\n");
      out.write("	              zeroLineColor: '#eeeeee'\n");
      out.write("	            }\n");
      out.write("	          }],\n");
      out.write("	          yAxes: [{\n");
      out.write("	            display: true,\n");
      out.write("	            ticks: {\n");
      out.write("	              display: true,\n");
      out.write("	              autoSkip: false,\n");
      out.write("	              maxRotation: 0,\n");
      out.write("	              stepSize: 100,\n");
      out.write("	              fontColor: \"#000\",\n");
      out.write("	              fontSize: 14,\n");
      out.write("	              padding: 18,\n");
      out.write("	              stepSize: 1000,\n");
      out.write("	              max: 3000,\n");
      out.write("	              fontSize: 10,\n");
      out.write("	              fontColor: \"#b1b0b0\",\n");
      out.write("	              callback: function(value) {\n");
      out.write("	                var ranges = [\n");
      out.write("	                    { divider: 1e6, suffix: 'M' },\n");
      out.write("	                    { divider: 1e3, suffix: 'k' }\n");
      out.write("	                ];\n");
      out.write("	                function formatNumber(n) {\n");
      out.write("	                    for (var i = 0; i < ranges.length; i++) {\n");
      out.write("	                      if (n >= ranges[i].divider) {\n");
      out.write("	                          return (n / ranges[i].divider).toString() + ranges[i].suffix;\n");
      out.write("	                      }\n");
      out.write("	                    }\n");
      out.write("	                    return n;\n");
      out.write("	                }\n");
      out.write("	                return formatNumber(value);\n");
      out.write("	              }\n");
      out.write("	            },\n");
      out.write("	            gridLines: {\n");
      out.write("	              drawBorder: false,\n");
      out.write("	              color: \"#f8f8f8\",\n");
      out.write("	              zeroLineColor: \"#f8f8f8\"\n");
      out.write("	            }\n");
      out.write("	          }]\n");
      out.write("	        },\n");
      out.write("	        legend: {\n");
      out.write("	          display: false\n");
      out.write("	        },\n");
      out.write("	        tooltips: {\n");
      out.write("	          enabled: true\n");
      out.write("	        },\n");
      out.write("	        elements: {\n");
      out.write("	          line: {\n");
      out.write("	            tension: 0\n");
      out.write("	          },\n");
      out.write("	          point: {\n");
      out.write("	            radius: 0\n");
      out.write("	          }\n");
      out.write("	        }\n");
      out.write("	      }\n");
      out.write("	      var balanceChartCanvas = $(\"#balance-chart\").get(0).getContext(\"2d\");\n");
      out.write("	      var balanceChart = new Chart(balanceChartCanvas, {\n");
      out.write("	        type: 'line',\n");
      out.write("	        data: areaData,\n");
      out.write("	        options: areaOptions\n");
      out.write("	      });\n");
      out.write("	    }\n");
      out.write("\n");
      out.write("	    if ($(\"#task-chart\").length) {\n");
      out.write("	      var taskChartCanvas = $(\"#task-chart\").get(0).getContext(\"2d\");\n");
      out.write("	      var taskChart = new Chart(taskChartCanvas, {\n");
      out.write("	        type: 'bar',\n");
      out.write("	        data: {\n");
      out.write("	          labels: [\n");
      out.write("	        	  ");
      if (_jspx_meth_c_005fforEach_005f6(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	        	  ],\n");
      out.write("	          datasets: [{\n");
      out.write("	              label: 'Profit',\n");
      out.write("	              data: [\n");
      out.write("	            	  ");
      if (_jspx_meth_c_005fforEach_005f7(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	            	  ],\n");
      out.write("	              backgroundColor: '#f83e37'\n");
      out.write("	            }\n");
      out.write("	          ]\n");
      out.write("	        },\n");
      out.write("	        options: {\n");
      out.write("	          responsive: true,\n");
      out.write("	          maintainAspectRatio: true,\n");
      out.write("	          layout: {\n");
      out.write("	            padding: {\n");
      out.write("	              left: 0,\n");
      out.write("	              right: 0,\n");
      out.write("	              top: 0,\n");
      out.write("	              bottom: 0\n");
      out.write("	            }\n");
      out.write("	          },\n");
      out.write("	          scales: {\n");
      out.write("	            yAxes: [{\n");
      out.write("	              display: true,\n");
      out.write("	              gridLines: {\n");
      out.write("	                drawBorder: false,\n");
      out.write("	                color: '#f1f3f9',\n");
      out.write("	                zeroLineColor: '#f1f3f9'\n");
      out.write("	              },\n");
      out.write("	              ticks: {\n");
      out.write("	                display: true,\n");
      out.write("	                fontColor: \"#9fa0a2\",\n");
      out.write("	                fontSize: 10,\n");
      out.write("	                padding: 0,\n");
      out.write("	                stepSize: 10,\n");
      out.write("	                min: -10,\n");
      out.write("	                max: 10\n");
      out.write("	              }\n");
      out.write("	            }],\n");
      out.write("	            xAxes: [{\n");
      out.write("	              display: false,\n");
      out.write("	              stacked: false,\n");
      out.write("	              categoryPercentage: 1,\n");
      out.write("	              ticks: {\n");
      out.write("	                display: false,\n");
      out.write("	                beginAtZero: false,\n");
      out.write("	                display: true,\n");
      out.write("	                padding: 10,\n");
      out.write("	                fontSize: 11\n");
      out.write("	              },\n");
      out.write("	              gridLines: {\n");
      out.write("	                color: \"rgba(0, 0, 0, 0)\",\n");
      out.write("	                display: false\n");
      out.write("	              },\n");
      out.write("	              position: 'bottom',\n");
      out.write("	              barPercentage: 0.7\n");
      out.write("	            }]\n");
      out.write("	          },\n");
      out.write("	          legend: {\n");
      out.write("	            display: false\n");
      out.write("	          },\n");
      out.write("	          elements: {\n");
      out.write("	            point: {\n");
      out.write("	              radius: 0\n");
      out.write("	            }\n");
      out.write("	          }\n");
      out.write("	        }\n");
      out.write("	      });\n");
      out.write("	    }\n");
      out.write("\n");
      out.write("	    if ($(\"#regional-chart\").length) {\n");
      out.write("	      var regionalChartCanvas = $(\"#regional-chart\").get(0).getContext(\"2d\");\n");
      out.write("	      var regionalChart = new Chart(regionalChartCanvas, {\n");
      out.write("	        type: 'horizontalBar',\n");
      out.write("	        data: {\n");
      out.write("	          labels: [\n");
      out.write("	        	  ");
      if (_jspx_meth_c_005fforEach_005f8(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	        	  ],\n");
      out.write("	          datasets: [\n");
      out.write("	            {\n");
      out.write("	              label: 'Max',\n");
      out.write("	              data: [\n");
      out.write("	            	  ");
      if (_jspx_meth_c_005fforEach_005f9(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	            	  ],\n");
      out.write("	              backgroundColor: '#1cbccd'\n");
      out.write("	            },\n");
      out.write("	            {\n");
      out.write("	              label: 'Min',\n");
      out.write("	              data: [\n");
      out.write("	            	  ");
      if (_jspx_meth_c_005fforEach_005f10(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	            	  ],\n");
      out.write("	              backgroundColor: '#ffbf36'\n");
      out.write("	            }\n");
      out.write("	          ]\n");
      out.write("	        },\n");
      out.write("	        options: {\n");
      out.write("	          responsive: true,\n");
      out.write("	          maintainAspectRatio: true,\n");
      out.write("	          layout: {\n");
      out.write("	            padding: {\n");
      out.write("	              left: -7,\n");
      out.write("	              right: 0,\n");
      out.write("	              top: 0,\n");
      out.write("	              bottom: 0\n");
      out.write("	            }\n");
      out.write("	          },\n");
      out.write("	          scales: {\n");
      out.write("	            yAxes: [{\n");
      out.write("	              display: true,\n");
      out.write("	              gridLines: {\n");
      out.write("	                display: false,\n");
      out.write("	                drawBorder: false\n");
      out.write("	              },\n");
      out.write("	              ticks: {\n");
      out.write("	                display: true,\n");
      out.write("	                min: 0,\n");
      out.write("	                max: 400,\n");
      out.write("	                stepSize: 100,\n");
      out.write("	                fontColor: \"#b1b0b0\",\n");
      out.write("	                fontSize: 10,\n");
      out.write("	                padding: 10\n");
      out.write("	              },\n");
      out.write("	              barPercentage: 1,\n");
      out.write("	              categoryPercentage: .6,\n");
      out.write("	            }],\n");
      out.write("	            xAxes: [{\n");
      out.write("	              display: true,\n");
      out.write("	              stacked: false,\n");
      out.write("	              ticks: {\n");
      out.write("	                display: false,\n");
      out.write("	                beginAtZero: true,\n");
      out.write("	                fontColor: \"#b1b0b0\",\n");
      out.write("	                fontSize: 10\n");
      out.write("	              },\n");
      out.write("	              gridLines: {\n");
      out.write("	                display: true,\n");
      out.write("	                drawBorder: false,\n");
      out.write("	                lineWidth: 1,\n");
      out.write("	                color: \"#f5f5f5\",\n");
      out.write("	                zeroLineColor: \"#f5f5f5\"\n");
      out.write("	              }\n");
      out.write("	            }]\n");
      out.write("	          },\n");
      out.write("	          legend: {\n");
      out.write("	            display: false\n");
      out.write("	          },\n");
      out.write("	          elements: {\n");
      out.write("	            point: {\n");
      out.write("	              radius: 3,\n");
      out.write("	              backgroundColor: '#ff4c5b'\n");
      out.write("	            }\n");
      out.write("	          },\n");
      out.write("	          legendCallback : function(chart) {\n");
      out.write("	            var text = [];\n");
      out.write("	              text.push('<div class=\"item me-4 d-flex align-items-center\">');\n");
      out.write("	                text.push('<div class=\"item-box me-2\" style=\" background-color: ' + chart.data.datasets[0].backgroundColor + ' \"></div><p class=\"text-black mb-0\"> ' + chart.data.datasets[0].label + '</p>');\n");
      out.write("	              text.push('</div>');\n");
      out.write("	              text.push('<div class=\"item d-flex align-items-center\">');\n");
      out.write("	                text.push('<div class=\"item-box me-2\" style=\" background-color: ' + chart.data.datasets[1].backgroundColor + '\"></div><p class=\"text-black mb-0\"> ' + chart.data.datasets[1].label + ' </p>');\n");
      out.write("	              text.push('</div>');\n");
      out.write("	            return text.join('');\n");
      out.write("	          }\n");
      out.write("	        },\n");
      out.write("	      });\n");
      out.write("	      document.querySelector('#regional-chart-legend').innerHTML = regionalChart.generateLegend();\n");
      out.write("	    }\n");
      out.write("\n");
      out.write("	    if ($(\"#activity-chart\").length) {\n");
      out.write("	      var activityChartCanvas = $(\"#activity-chart\").get(0).getContext(\"2d\");\n");
      out.write("	      var activityChart = new Chart(activityChartCanvas, {\n");
      out.write("	        type: 'bar',\n");
      out.write("	        data: {\n");
      out.write("	          labels: [\n");
      out.write("	        	  ");
      if (_jspx_meth_c_005fforEach_005f11(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	        	  ],\n");
      out.write("	          datasets: [{\n");
      out.write("	              label: 'Profit',\n");
      out.write("	              data: [\n");
      out.write("	            	  ");
      if (_jspx_meth_c_005fforEach_005f12(_jspx_page_context))
        return;
      out.write("\n");
      out.write("	            	  ],\n");
      out.write("	              backgroundColor: '#ffbf36'\n");
      out.write("	            }\n");
      out.write("	          ]\n");
      out.write("	        },\n");
      out.write("	        options: {\n");
      out.write("	          responsive: true,\n");
      out.write("	          maintainAspectRatio: true,\n");
      out.write("	          layout: {\n");
      out.write("	            padding: {\n");
      out.write("	              left: 0,\n");
      out.write("	              right: 0,\n");
      out.write("	              top: 0,\n");
      out.write("	              bottom: 0\n");
      out.write("	            }\n");
      out.write("	          },\n");
      out.write("	          scales: {\n");
      out.write("	            yAxes: [{\n");
      out.write("	              display: false,\n");
      out.write("	              gridLines: {\n");
      out.write("	                display: false,\n");
      out.write("	                drawBorder: false\n");
      out.write("	              },\n");
      out.write("	              ticks: {\n");
      out.write("	                display: false,\n");
      out.write("	                min: 0,\n");
      out.write("	                max: 600,\n");
      out.write("	                stepSize: 100,\n");
      out.write("	                fontColor: \"#fff\"\n");
      out.write("	              }\n");
      out.write("	            }],\n");
      out.write("	            xAxes: [{\n");
      out.write("	              display: false,\n");
      out.write("	              stacked: true,\n");
      out.write("	              ticks: {\n");
      out.write("	                beginAtZero: true,\n");
      out.write("	                fontColor: \"#fff\"\n");
      out.write("	              },\n");
      out.write("	              gridLines: {\n");
      out.write("	                color: \"rgba(0, 0, 0, 0)\",\n");
      out.write("	                display: false\n");
      out.write("	              },\n");
      out.write("	              barPercentage: .8,\n");
      out.write("	              categoryPercentage: .9,\n");
      out.write("	            }]\n");
      out.write("	          },\n");
      out.write("	          legend: {\n");
      out.write("	            display: false\n");
      out.write("	          },\n");
      out.write("	          elements: {\n");
      out.write("	            point: {\n");
      out.write("	              radius: 0\n");
      out.write("	            }\n");
      out.write("	          }\n");
      out.write("	        }\n");
      out.write("	      });\n");
      out.write("	    }\n");
      out.write("\n");
      out.write("	  });\n");
      out.write("	})(jQuery);\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/template/view/admin/_index.jsp(16,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/template/view/admin/_index.jsp(16,12) '${list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/template/view/admin/_index.jsp(16,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("l");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	        	  \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${l[0] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\n");
            out.write("	        	  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/template/view/admin/_index.jsp(25,16) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/template/view/admin/_index.jsp(25,16) '${list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/template/view/admin/_index.jsp(25,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("l");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	            	  ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${l[3] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(", \n");
            out.write("	            	  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(null);
      // /WEB-INF/template/view/admin/_index.jsp(34,16) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/template/view/admin/_index.jsp(34,16) '${list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/template/view/admin/_index.jsp(34,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("l");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	            	  ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${l[3] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(", \n");
            out.write("	            	  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent(null);
      // /WEB-INF/template/view/admin/_index.jsp(43,19) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/template/view/admin/_index.jsp(43,19) '${list }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/template/view/admin/_index.jsp(43,19) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("l");
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("		            	  ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${l[4] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(", \n");
            out.write("		            	  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f4_reused = false;
    try {
      _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f4.setParent(null);
      // /WEB-INF/template/view/admin/_index.jsp(112,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/template/view/admin/_index.jsp(112,10) '${listyear }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listyear }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/template/view/admin/_index.jsp(112,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setVar("y");
      int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
        if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	        	  \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${y[0] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\n");
            out.write("	        	  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f4);
      _jspx_th_c_005fforEach_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f5 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f5_reused = false;
    try {
      _jspx_th_c_005fforEach_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f5.setParent(null);
      // /WEB-INF/template/view/admin/_index.jsp(119,15) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/template/view/admin/_index.jsp(119,15) '${listmonth}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listmonth}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/template/view/admin/_index.jsp(119,15) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setVar("y");
      int[] _jspx_push_body_count_c_005fforEach_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f5 = _jspx_th_c_005fforEach_005f5.doStartTag();
        if (_jspx_eval_c_005fforEach_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	            	  ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${y[4] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(", \n");
            out.write("	            	  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f5.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f5);
      _jspx_th_c_005fforEach_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f6 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f6_reused = false;
    try {
      _jspx_th_c_005fforEach_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f6.setParent(null);
      // /WEB-INF/template/view/admin/_index.jsp(220,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f6.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/template/view/admin/_index.jsp(220,12) '${listmonth }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listmonth }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/template/view/admin/_index.jsp(220,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f6.setVar("y");
      int[] _jspx_push_body_count_c_005fforEach_005f6 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f6 = _jspx_th_c_005fforEach_005f6.doStartTag();
        if (_jspx_eval_c_005fforEach_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	        	  \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${y[0] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\n");
            out.write("	        	  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f6.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f6[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f6.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f6.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f6);
      _jspx_th_c_005fforEach_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f7 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f7_reused = false;
    try {
      _jspx_th_c_005fforEach_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f7.setParent(null);
      // /WEB-INF/template/view/admin/_index.jsp(227,16) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f7.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/template/view/admin/_index.jsp(227,16) '${listmonth}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listmonth}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/template/view/admin/_index.jsp(227,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f7.setVar("y");
      int[] _jspx_push_body_count_c_005fforEach_005f7 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f7 = _jspx_th_c_005fforEach_005f7.doStartTag();
        if (_jspx_eval_c_005fforEach_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	            	  ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${y[5] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(", \n");
            out.write("	            	  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f7.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f7[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f7.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f7.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f7);
      _jspx_th_c_005fforEach_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f8 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f8_reused = false;
    try {
      _jspx_th_c_005fforEach_005f8.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f8.setParent(null);
      // /WEB-INF/template/view/admin/_index.jsp(301,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f8.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/template/view/admin/_index.jsp(301,12) '${listsale }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listsale }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/template/view/admin/_index.jsp(301,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f8.setVar("c");
      int[] _jspx_push_body_count_c_005fforEach_005f8 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f8 = _jspx_th_c_005fforEach_005f8.doStartTag();
        if (_jspx_eval_c_005fforEach_005f8 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	        	  \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c[0] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\n");
            out.write("	        	  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f8.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f8[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f8.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f8.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f8);
      _jspx_th_c_005fforEach_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f8, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f9(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f9 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f9_reused = false;
    try {
      _jspx_th_c_005fforEach_005f9.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f9.setParent(null);
      // /WEB-INF/template/view/admin/_index.jsp(309,16) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f9.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/template/view/admin/_index.jsp(309,16) '${listsale}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listsale}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/template/view/admin/_index.jsp(309,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f9.setVar("c");
      int[] _jspx_push_body_count_c_005fforEach_005f9 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f9 = _jspx_th_c_005fforEach_005f9.doStartTag();
        if (_jspx_eval_c_005fforEach_005f9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	            	  ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c[4] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(", \n");
            out.write("	            	  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f9.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f9[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f9.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f9.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f9);
      _jspx_th_c_005fforEach_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f9, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f10(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f10 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f10_reused = false;
    try {
      _jspx_th_c_005fforEach_005f10.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f10.setParent(null);
      // /WEB-INF/template/view/admin/_index.jsp(318,16) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f10.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/template/view/admin/_index.jsp(318,16) '${listsale}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listsale}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/template/view/admin/_index.jsp(318,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f10.setVar("c");
      int[] _jspx_push_body_count_c_005fforEach_005f10 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f10 = _jspx_th_c_005fforEach_005f10.doStartTag();
        if (_jspx_eval_c_005fforEach_005f10 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	            	  ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${c[3] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(", \n");
            out.write("	            	  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f10.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f10.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f10[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f10.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f10.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f10);
      _jspx_th_c_005fforEach_005f10_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f10, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f10_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f11(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f11 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f11_reused = false;
    try {
      _jspx_th_c_005fforEach_005f11.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f11.setParent(null);
      // /WEB-INF/template/view/admin/_index.jsp(404,12) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f11.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/template/view/admin/_index.jsp(404,12) '${listquarter }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listquarter }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/template/view/admin/_index.jsp(404,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f11.setVar("q");
      int[] _jspx_push_body_count_c_005fforEach_005f11 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f11 = _jspx_th_c_005fforEach_005f11.doStartTag();
        if (_jspx_eval_c_005fforEach_005f11 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	        	  \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${q[0] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\",\n");
            out.write("	        	  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f11.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f11.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f11[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f11.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f11.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f11);
      _jspx_th_c_005fforEach_005f11_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f11, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f11_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f12(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f12 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f12_reused = false;
    try {
      _jspx_th_c_005fforEach_005f12.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f12.setParent(null);
      // /WEB-INF/template/view/admin/_index.jsp(411,16) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f12.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/template/view/admin/_index.jsp(411,16) '${listquarter }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${listquarter }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/template/view/admin/_index.jsp(411,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f12.setVar("q");
      int[] _jspx_push_body_count_c_005fforEach_005f12 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f12 = _jspx_th_c_005fforEach_005f12.doStartTag();
        if (_jspx_eval_c_005fforEach_005f12 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("	            	  ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${q[2]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(",\n");
            out.write("	            	  ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f12.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f12.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f12[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f12.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f12.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f12);
      _jspx_th_c_005fforEach_005f12_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f12, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f12_reused);
    }
    return false;
  }
}
